# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindowinz.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BrewPi(object):
    def setupUi(self, BrewPi):
        BrewPi.setObjectName("BrewPi")
        BrewPi.resize(669, 449)
        self.centralWidget = QtWidgets.QWidget(BrewPi)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.tab_3)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lcd_HTL = QtWidgets.QLCDNumber(self.tab_3)
        self.lcd_HTL.setAutoFillBackground(True)
        self.lcd_HTL.setSmallDecimalPoint(True)
        self.lcd_HTL.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_HTL.setObjectName("lcd_HTL")
        self.horizontalLayout_3.addWidget(self.lcd_HTL)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_4.addWidget(self.label_26)
        self.lcd_HTL2 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcd_HTL2.setAutoFillBackground(True)
        self.lcd_HTL2.setSmallDecimalPoint(True)
        self.lcd_HTL2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_HTL2.setObjectName("lcd_HTL2")
        self.horizontalLayout_4.addWidget(self.lcd_HTL2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.lcd_MASH = QtWidgets.QLCDNumber(self.tab_3)
        self.lcd_MASH.setAutoFillBackground(True)
        self.lcd_MASH.setSmallDecimalPoint(True)
        self.lcd_MASH.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_MASH.setObjectName("lcd_MASH")
        self.horizontalLayout_5.addWidget(self.lcd_MASH)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.lcd_MASH2 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcd_MASH2.setAutoFillBackground(True)
        self.lcd_MASH2.setSmallDecimalPoint(True)
        self.lcd_MASH2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_MASH2.setObjectName("lcd_MASH2")
        self.horizontalLayout_7.addWidget(self.lcd_MASH2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.lcd_KETTLE = QtWidgets.QLCDNumber(self.tab_3)
        self.lcd_KETTLE.setAutoFillBackground(True)
        self.lcd_KETTLE.setSmallDecimalPoint(True)
        self.lcd_KETTLE.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_KETTLE.setObjectName("lcd_KETTLE")
        self.horizontalLayout_8.addWidget(self.lcd_KETTLE)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lcd_KETTLE2 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcd_KETTLE2.setAutoFillBackground(True)
        self.lcd_KETTLE2.setSmallDecimalPoint(True)
        self.lcd_KETTLE2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_KETTLE2.setObjectName("lcd_KETTLE2")
        self.horizontalLayout_6.addWidget(self.lcd_KETTLE2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_28.setSpacing(6)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_28.addWidget(self.label_10)
        self.lcd_time_KETTLE = QtWidgets.QLCDNumber(self.tab_3)
        self.lcd_time_KETTLE.setAutoFillBackground(True)
        self.lcd_time_KETTLE.setSmallDecimalPoint(True)
        self.lcd_time_KETTLE.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_time_KETTLE.setObjectName("lcd_time_KETTLE")
        self.horizontalLayout_28.addWidget(self.lcd_time_KETTLE)
        self.verticalLayout.addLayout(self.horizontalLayout_28)
        self.pushButtonStart = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.verticalLayout.addWidget(self.pushButtonStart)
        self.pushButtonPause = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonPause.setEnabled(False)
        self.pushButtonPause.setObjectName("pushButtonPause")
        self.verticalLayout.addWidget(self.pushButtonPause)
        self.pushButtonStop = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonStop.setEnabled(False)
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.verticalLayout.addWidget(self.pushButtonStop)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_tempHTL = QtWidgets.QLabel(self.tab_5)
        self.label_tempHTL.setObjectName("label_tempHTL")
        self.horizontalLayout_10.addWidget(self.label_tempHTL)
        self.horizontalSlider_tempHTL = QtWidgets.QSlider(self.tab_5)
        self.horizontalSlider_tempHTL.setMaximum(100)
        self.horizontalSlider_tempHTL.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_tempHTL.setObjectName("horizontalSlider_tempHTL")
        self.horizontalLayout_10.addWidget(self.horizontalSlider_tempHTL)
        self.label_value_tempHTL = QtWidgets.QLabel(self.tab_5)
        self.label_value_tempHTL.setObjectName("label_value_tempHTL")
        self.horizontalLayout_10.addWidget(self.label_value_tempHTL)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_tempHTL2 = QtWidgets.QLabel(self.tab_5)
        self.label_tempHTL2.setObjectName("label_tempHTL2")
        self.horizontalLayout_11.addWidget(self.label_tempHTL2)
        self.horizontalSlider_tempHTL2 = QtWidgets.QSlider(self.tab_5)
        self.horizontalSlider_tempHTL2.setMaximum(100)
        self.horizontalSlider_tempHTL2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_tempHTL2.setObjectName("horizontalSlider_tempHTL2")
        self.horizontalLayout_11.addWidget(self.horizontalSlider_tempHTL2)
        self.label_value_tempHTL2 = QtWidgets.QLabel(self.tab_5)
        self.label_value_tempHTL2.setObjectName("label_value_tempHTL2")
        self.horizontalLayout_11.addWidget(self.label_value_tempHTL2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_tempMASH = QtWidgets.QLabel(self.tab_5)
        self.label_tempMASH.setObjectName("label_tempMASH")
        self.horizontalLayout_12.addWidget(self.label_tempMASH)
        self.horizontalSlider_tempMASH1_g = QtWidgets.QSlider(self.tab_5)
        self.horizontalSlider_tempMASH1_g.setMaximum(100)
        self.horizontalSlider_tempMASH1_g.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_tempMASH1_g.setObjectName("horizontalSlider_tempMASH1_g")
        self.horizontalLayout_12.addWidget(self.horizontalSlider_tempMASH1_g)
        self.label_value_tempMASH1_g = QtWidgets.QLabel(self.tab_5)
        self.label_value_tempMASH1_g.setObjectName("label_value_tempMASH1_g")
        self.horizontalLayout_12.addWidget(self.label_value_tempMASH1_g)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_tempMASH2 = QtWidgets.QLabel(self.tab_5)
        self.label_tempMASH2.setObjectName("label_tempMASH2")
        self.horizontalLayout_13.addWidget(self.label_tempMASH2)
        self.horizontalSlider_tempMASH1_d = QtWidgets.QSlider(self.tab_5)
        self.horizontalSlider_tempMASH1_d.setMaximum(100)
        self.horizontalSlider_tempMASH1_d.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_tempMASH1_d.setObjectName("horizontalSlider_tempMASH1_d")
        self.horizontalLayout_13.addWidget(self.horizontalSlider_tempMASH1_d)
        self.label_value_tempMASH1_d = QtWidgets.QLabel(self.tab_5)
        self.label_value_tempMASH1_d.setObjectName("label_value_tempMASH1_d")
        self.horizontalLayout_13.addWidget(self.label_value_tempMASH1_d)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_2 = QtWidgets.QLabel(self.tab_5)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_19.addWidget(self.label_2)
        self.horizontalSlider_tempMASH2_g = QtWidgets.QSlider(self.tab_5)
        self.horizontalSlider_tempMASH2_g.setMaximum(100)
        self.horizontalSlider_tempMASH2_g.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_tempMASH2_g.setObjectName("horizontalSlider_tempMASH2_g")
        self.horizontalLayout_19.addWidget(self.horizontalSlider_tempMASH2_g)
        self.label_value_tempMASH2_g = QtWidgets.QLabel(self.tab_5)
        self.label_value_tempMASH2_g.setObjectName("label_value_tempMASH2_g")
        self.horizontalLayout_19.addWidget(self.label_value_tempMASH2_g)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_20.addWidget(self.label_7)
        self.horizontalSlider_tempMASH2_d = QtWidgets.QSlider(self.tab_5)
        self.horizontalSlider_tempMASH2_d.setMaximum(100)
        self.horizontalSlider_tempMASH2_d.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_tempMASH2_d.setObjectName("horizontalSlider_tempMASH2_d")
        self.horizontalLayout_20.addWidget(self.horizontalSlider_tempMASH2_d)
        self.label_value_tempMASH2_d = QtWidgets.QLabel(self.tab_5)
        self.label_value_tempMASH2_d.setObjectName("label_value_tempMASH2_d")
        self.horizontalLayout_20.addWidget(self.label_value_tempMASH2_d)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_21.setSpacing(6)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_21.addWidget(self.label_8)
        self.horizontalSlider_tempMASH3_g = QtWidgets.QSlider(self.tab_5)
        self.horizontalSlider_tempMASH3_g.setMaximum(100)
        self.horizontalSlider_tempMASH3_g.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_tempMASH3_g.setObjectName("horizontalSlider_tempMASH3_g")
        self.horizontalLayout_21.addWidget(self.horizontalSlider_tempMASH3_g)
        self.label_value_tempMASH3_g = QtWidgets.QLabel(self.tab_5)
        self.label_value_tempMASH3_g.setObjectName("label_value_tempMASH3_g")
        self.horizontalLayout_21.addWidget(self.label_value_tempMASH3_g)
        self.verticalLayout_3.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_22.setSpacing(6)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_22.addWidget(self.label_9)
        self.horizontalSlider_tempMASH3_d = QtWidgets.QSlider(self.tab_5)
        self.horizontalSlider_tempMASH3_d.setMaximum(100)
        self.horizontalSlider_tempMASH3_d.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_tempMASH3_d.setObjectName("horizontalSlider_tempMASH3_d")
        self.horizontalLayout_22.addWidget(self.horizontalSlider_tempMASH3_d)
        self.label_value_tempMASH3_d = QtWidgets.QLabel(self.tab_5)
        self.label_value_tempMASH3_d.setObjectName("label_value_tempMASH3_d")
        self.horizontalLayout_22.addWidget(self.label_value_tempMASH3_d)
        self.verticalLayout_3.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_tempKETTLE = QtWidgets.QLabel(self.tab_5)
        self.label_tempKETTLE.setObjectName("label_tempKETTLE")
        self.horizontalLayout_14.addWidget(self.label_tempKETTLE)
        self.horizontalSlider_tempKETTLE = QtWidgets.QSlider(self.tab_5)
        self.horizontalSlider_tempKETTLE.setMaximum(100)
        self.horizontalSlider_tempKETTLE.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_tempKETTLE.setObjectName("horizontalSlider_tempKETTLE")
        self.horizontalLayout_14.addWidget(self.horizontalSlider_tempKETTLE)
        self.label_value_tempKETTLE = QtWidgets.QLabel(self.tab_5)
        self.label_value_tempKETTLE.setObjectName("label_value_tempKETTLE")
        self.horizontalLayout_14.addWidget(self.label_value_tempKETTLE)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_tempKETTLE2 = QtWidgets.QLabel(self.tab_5)
        self.label_tempKETTLE2.setObjectName("label_tempKETTLE2")
        self.horizontalLayout_15.addWidget(self.label_tempKETTLE2)
        self.horizontalSlider_tempKETTLE2 = QtWidgets.QSlider(self.tab_5)
        self.horizontalSlider_tempKETTLE2.setMaximum(100)
        self.horizontalSlider_tempKETTLE2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_tempKETTLE2.setObjectName("horizontalSlider_tempKETTLE2")
        self.horizontalLayout_15.addWidget(self.horizontalSlider_tempKETTLE2)
        self.label_value_tempKETTLE2 = QtWidgets.QLabel(self.tab_5)
        self.label_value_tempKETTLE2.setObjectName("label_value_tempKETTLE2")
        self.horizontalLayout_15.addWidget(self.label_value_tempKETTLE2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_czasMASH1 = QtWidgets.QLabel(self.tab_5)
        self.label_czasMASH1.setObjectName("label_czasMASH1")
        self.horizontalLayout_16.addWidget(self.label_czasMASH1)
        self.horizontalSlider_czasMASH1 = QtWidgets.QSlider(self.tab_5)
        self.horizontalSlider_czasMASH1.setMaximum(360)
        self.horizontalSlider_czasMASH1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_czasMASH1.setObjectName("horizontalSlider_czasMASH1")
        self.horizontalLayout_16.addWidget(self.horizontalSlider_czasMASH1)
        self.label_value_czasMASH1 = QtWidgets.QLabel(self.tab_5)
        self.label_value_czasMASH1.setObjectName("label_value_czasMASH1")
        self.horizontalLayout_16.addWidget(self.label_value_czasMASH1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_czasMASH2 = QtWidgets.QLabel(self.tab_5)
        self.label_czasMASH2.setObjectName("label_czasMASH2")
        self.horizontalLayout_17.addWidget(self.label_czasMASH2)
        self.horizontalSlider_czasMASH2 = QtWidgets.QSlider(self.tab_5)
        self.horizontalSlider_czasMASH2.setMaximum(360)
        self.horizontalSlider_czasMASH2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_czasMASH2.setObjectName("horizontalSlider_czasMASH2")
        self.horizontalLayout_17.addWidget(self.horizontalSlider_czasMASH2)
        self.label_value_czasMASH2 = QtWidgets.QLabel(self.tab_5)
        self.label_value_czasMASH2.setObjectName("label_value_czasMASH2")
        self.horizontalLayout_17.addWidget(self.label_value_czasMASH2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_czasMASH3 = QtWidgets.QLabel(self.tab_5)
        self.label_czasMASH3.setObjectName("label_czasMASH3")
        self.horizontalLayout_18.addWidget(self.label_czasMASH3)
        self.horizontalSlider_czasMASH3 = QtWidgets.QSlider(self.tab_5)
        self.horizontalSlider_czasMASH3.setMaximum(360)
        self.horizontalSlider_czasMASH3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_czasMASH3.setObjectName("horizontalSlider_czasMASH3")
        self.horizontalLayout_18.addWidget(self.horizontalSlider_czasMASH3)
        self.label_value_czasMASH3 = QtWidgets.QLabel(self.tab_5)
        self.label_value_czasMASH3.setObjectName("label_value_czasMASH3")
        self.horizontalLayout_18.addWidget(self.label_value_czasMASH3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_czasKETTLE = QtWidgets.QLabel(self.tab_5)
        self.label_czasKETTLE.setObjectName("label_czasKETTLE")
        self.horizontalLayout_9.addWidget(self.label_czasKETTLE)
        self.horizontalSlider_czasKETTLE = QtWidgets.QSlider(self.tab_5)
        self.horizontalSlider_czasKETTLE.setMaximum(360)
        self.horizontalSlider_czasKETTLE.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_czasKETTLE.setObjectName("horizontalSlider_czasKETTLE")
        self.horizontalLayout_9.addWidget(self.horizontalSlider_czasKETTLE)
        self.label_value_czasKETTLE = QtWidgets.QLabel(self.tab_5)
        self.label_value_czasKETTLE.setObjectName("label_value_czasKETTLE")
        self.horizontalLayout_9.addWidget(self.label_value_czasKETTLE)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_4.sizePolicy().hasHeightForWidth())
        self.tab_4.setSizePolicy(sizePolicy)
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_23.setSpacing(6)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.checkBox_zH2O_HTL = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_zH2O_HTL.setSizeIncrement(QtCore.QSize(10, 10))
        self.checkBox_zH2O_HTL.setBaseSize(QtCore.QSize(0, 0))
        self.checkBox_zH2O_HTL.setIconSize(QtCore.QSize(0, 0))
        self.checkBox_zH2O_HTL.setTristate(False)
        self.checkBox_zH2O_HTL.setObjectName("checkBox_zH2O_HTL")
        self.horizontalLayout_23.addWidget(self.checkBox_zH2O_HTL)
        self.checkBox_zHTL_OUT = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_zHTL_OUT.setObjectName("checkBox_zHTL_OUT")
        self.horizontalLayout_23.addWidget(self.checkBox_zHTL_OUT)
        self.checkBox_zMASH_IN = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_zMASH_IN.setObjectName("checkBox_zMASH_IN")
        self.horizontalLayout_23.addWidget(self.checkBox_zMASH_IN)
        self.verticalLayout_2.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_24.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_24.setSpacing(6)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.checkBox_zMASH_OUT = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_zMASH_OUT.setObjectName("checkBox_zMASH_OUT")
        self.horizontalLayout_24.addWidget(self.checkBox_zMASH_OUT)
        self.checkBox_zKETTLE_IN = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_zKETTLE_IN.setObjectName("checkBox_zKETTLE_IN")
        self.horizontalLayout_24.addWidget(self.checkBox_zKETTLE_IN)
        self.checkBox_zKETTLE_OUT = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_zKETTLE_OUT.setObjectName("checkBox_zKETTLE_OUT")
        self.horizontalLayout_24.addWidget(self.checkBox_zKETTLE_OUT)
        self.verticalLayout_2.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_25.setSpacing(6)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.checkBox_zKLA_KETTLE_OUT = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_zKLA_KETTLE_OUT.setObjectName("checkBox_zKLA_KETTLE_OUT")
        self.horizontalLayout_25.addWidget(self.checkBox_zKLA_KETTLE_OUT)
        self.checkBox_zKLA_KETTLE_IN = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_zKLA_KETTLE_IN.setObjectName("checkBox_zKLA_KETTLE_IN")
        self.horizontalLayout_25.addWidget(self.checkBox_zKLA_KETTLE_IN)
        self.checkBox_zH2O_COOLER = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_zH2O_COOLER.setObjectName("checkBox_zH2O_COOLER")
        self.horizontalLayout_25.addWidget(self.checkBox_zH2O_COOLER)
        self.verticalLayout_2.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_26.setSpacing(6)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.checkBox_pompa_HTL_MASH = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_pompa_HTL_MASH.setObjectName("checkBox_pompa_HTL_MASH")
        self.horizontalLayout_26.addWidget(self.checkBox_pompa_HTL_MASH)
        self.checkBox_pompa_KETTLE = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_pompa_KETTLE.setObjectName("checkBox_pompa_KETTLE")
        self.horizontalLayout_26.addWidget(self.checkBox_pompa_KETTLE)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_zSTOP_ALL = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_zSTOP_ALL.setObjectName("pushButton_zSTOP_ALL")
        self.verticalLayout_4.addWidget(self.pushButton_zSTOP_ALL)
        self.pushButton_pSTOP_ALL = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_pSTOP_ALL.setObjectName("pushButton_pSTOP_ALL")
        self.verticalLayout_4.addWidget(self.pushButton_pSTOP_ALL)
        self.horizontalLayout_26.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_26)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.progressBar_clean_process = QtWidgets.QProgressBar(self.tab)
        self.progressBar_clean_process.setProperty("value", 0)
        self.progressBar_clean_process.setObjectName("progressBar_clean_process")
        self.verticalLayout_5.addWidget(self.progressBar_clean_process)
        self.pushButton_start_clean = QtWidgets.QPushButton(self.tab)
        self.pushButton_start_clean.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_start_clean.setObjectName("pushButton_start_clean")
        self.verticalLayout_5.addWidget(self.pushButton_start_clean)
        self.pushButton_stop_clean = QtWidgets.QPushButton(self.tab)
        self.pushButton_stop_clean.setObjectName("pushButton_stop_clean")
        self.verticalLayout_5.addWidget(self.pushButton_stop_clean)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        BrewPi.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(BrewPi)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 669, 19))
        self.menuBar.setObjectName("menuBar")
        BrewPi.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(BrewPi)
        self.mainToolBar.setObjectName("mainToolBar")
        BrewPi.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(BrewPi)
        self.statusBar.setObjectName("statusBar")
        BrewPi.setStatusBar(self.statusBar)

        self.retranslateUi(BrewPi)
        self.tabWidget.setCurrentIndex(0)
        self.horizontalSlider_tempHTL.sliderMoved['int'].connect(self.label_value_tempHTL.setNum)
        self.horizontalSlider_tempHTL2.sliderMoved['int'].connect(self.label_value_tempHTL2.setNum)
        self.horizontalSlider_tempMASH1_g.sliderMoved['int'].connect(self.label_value_tempMASH1_g.setNum)
        self.horizontalSlider_tempMASH1_d.sliderMoved['int'].connect(self.label_value_tempMASH1_d.setNum)
        self.horizontalSlider_tempKETTLE.sliderMoved['int'].connect(self.label_value_tempKETTLE.setNum)
        self.horizontalSlider_tempKETTLE2.sliderMoved['int'].connect(self.label_value_tempKETTLE2.setNum)
        self.horizontalSlider_czasMASH1.sliderMoved['int'].connect(self.label_value_czasMASH1.setNum)
        self.horizontalSlider_czasMASH2.sliderMoved['int'].connect(self.label_value_czasMASH2.setNum)
        self.horizontalSlider_czasMASH3.sliderMoved['int'].connect(self.label_value_czasMASH3.setNum)
        self.horizontalSlider_czasKETTLE.sliderMoved['int'].connect(self.label_value_czasKETTLE.setNum)
        self.horizontalSlider_tempMASH2_g.sliderMoved['int'].connect(self.label_value_tempMASH1_g.setNum)
        self.horizontalSlider_tempMASH2_d.sliderMoved['int'].connect(self.label_value_tempMASH2_d.setNum)
        self.horizontalSlider_tempMASH3_g.sliderMoved['int'].connect(self.label_value_tempMASH3_g.setNum)
        self.horizontalSlider_tempMASH3_d.sliderMoved['int'].connect(self.label_value_tempMASH3_d.setNum)
        self.pushButton_zSTOP_ALL.clicked['bool'].connect(self.checkBox_zH2O_COOLER.setChecked)
        QtCore.QMetaObject.connectSlotsByName(BrewPi)

    def retranslateUi(self, BrewPi):
        _translate = QtCore.QCoreApplication.translate
        BrewPi.setWindowTitle(_translate("BrewPi", "MainWindowinz"))
        self.label.setText(_translate("BrewPi", "Temperatura HTL_1 [°C]"))
        self.label_26.setText(_translate("BrewPi", "Temperatura HTL_2 [°C]"))
        self.label_3.setText(_translate("BrewPi", "Temperatura MASH_1 [°C]"))
        self.label_4.setText(_translate("BrewPi", "Temperatura MASH_2 [°C]"))
        self.label_5.setText(_translate("BrewPi", "Temperatura KETTLE_1 [°C]"))
        self.label_6.setText(_translate("BrewPi", "Temperatura KETTLE_2 [°C]"))
        self.label_10.setText(_translate("BrewPi", "Czas warzenia [min]"))
        self.pushButtonStart.setText(_translate("BrewPi", "Start"))
        self.pushButtonPause.setText(_translate("BrewPi", "Pauza"))
        self.pushButtonStop.setText(_translate("BrewPi", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("BrewPi", "Ekran główny"))
        self.label_tempHTL.setText(_translate("BrewPi", "Temp HTL.góra"))
        self.label_value_tempHTL.setText(_translate("BrewPi", "0"))
        self.label_tempHTL2.setText(_translate("BrewPi", "Temp HTL.dół"))
        self.label_value_tempHTL2.setText(_translate("BrewPi", "0"))
        self.label_tempMASH.setText(_translate("BrewPi", "Temp MASH.1.góra"))
        self.label_value_tempMASH1_g.setText(_translate("BrewPi", "0"))
        self.label_tempMASH2.setText(_translate("BrewPi", "Temp MASH.1.dół"))
        self.label_value_tempMASH1_d.setText(_translate("BrewPi", "0"))
        self.label_2.setText(_translate("BrewPi", "Temp MASH.2.góra"))
        self.label_value_tempMASH2_g.setText(_translate("BrewPi", "0"))
        self.label_7.setText(_translate("BrewPi", "Temp MASH.2.dół"))
        self.label_value_tempMASH2_d.setText(_translate("BrewPi", "0"))
        self.label_8.setText(_translate("BrewPi", "Temp MASH.OUT.góra"))
        self.label_value_tempMASH3_g.setText(_translate("BrewPi", "0"))
        self.label_9.setText(_translate("BrewPi", "Temp MASH.OUT.dół"))
        self.label_value_tempMASH3_d.setText(_translate("BrewPi", "0"))
        self.label_tempKETTLE.setText(_translate("BrewPi", "Temp KETTLE.góra"))
        self.label_value_tempKETTLE.setText(_translate("BrewPi", "0"))
        self.label_tempKETTLE2.setText(_translate("BrewPi", "Temp KETTLE.dół"))
        self.label_value_tempKETTLE2.setText(_translate("BrewPi", "0"))
        self.label_czasMASH1.setText(_translate("BrewPi", "Czas MASH.1"))
        self.label_value_czasMASH1.setText(_translate("BrewPi", "0"))
        self.label_czasMASH2.setText(_translate("BrewPi", "Czas MASH.2"))
        self.label_value_czasMASH2.setText(_translate("BrewPi", "0"))
        self.label_czasMASH3.setText(_translate("BrewPi", "Czas MASH.OUT"))
        self.label_value_czasMASH3.setText(_translate("BrewPi", "0"))
        self.label_czasKETTLE.setText(_translate("BrewPi", "Czas KETTLE"))
        self.label_value_czasKETTLE.setText(_translate("BrewPi", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("BrewPi", "Ustawienia"))
        self.checkBox_zH2O_HTL.setText(_translate("BrewPi", "Zawór H2O->HTL"))
        self.checkBox_zHTL_OUT.setText(_translate("BrewPi", "Zawór HTL_OUT"))
        self.checkBox_zMASH_IN.setText(_translate("BrewPi", "Zawór MASH_IN"))
        self.checkBox_zMASH_OUT.setText(_translate("BrewPi", "Zawór MASH_OUT"))
        self.checkBox_zKETTLE_IN.setText(_translate("BrewPi", "Zawór KETTLE_IN"))
        self.checkBox_zKETTLE_OUT.setText(_translate("BrewPi", "Zawór KETTLE_OUT"))
        self.checkBox_zKLA_KETTLE_OUT.setText(_translate("BrewPi", "Zawór KLAROWANIE_KETTLE_OUT"))
        self.checkBox_zKLA_KETTLE_IN.setText(_translate("BrewPi", "Zawór KLAROWANIE_KETTLE_IN"))
        self.checkBox_zH2O_COOLER.setText(_translate("BrewPi", "Zawór H2O->Chłodnica"))
        self.checkBox_pompa_HTL_MASH.setText(_translate("BrewPi", "Pompa 1 (HTL i MASH)"))
        self.checkBox_pompa_KETTLE.setText(_translate("BrewPi", "Pompa 2 (KETTLE)"))
        self.pushButton_zSTOP_ALL.setText(_translate("BrewPi", "Wyłączenie zaworów"))
        self.pushButton_pSTOP_ALL.setText(_translate("BrewPi", "Wyłączenie pomp"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("BrewPi", "Zawory i pompy"))
        self.pushButton_start_clean.setText(_translate("BrewPi", "Start"))
        self.pushButton_stop_clean.setText(_translate("BrewPi", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("BrewPi", "Czyszczenie"))

